name: alati_app
description: A Flutter app with drag-and-drop pie chart.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"  # Replace with your desired SDK version

dependencies:
  flutter:
    sdk: flutter
  flutter_pie_chart: ^0.0.1
  draggable_scrollbar: ^0.1.0
  fl_chart: ^0.40.0 # Use the latest version available
  reorderables:
  charts_flutter: 0.12.0
  excel: ^3.0.0
  file_picker: ^6.1.1
  sqflite: ^2.0.0+3
  path_provider: ^2.0.6
  http: ^0.13.3
  moor: ^4.6.1+1
  flutter_bloc: ^8.1.4
  shared_preferences: ^2.2.2
  printing: ^5.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true